[package]
name = "rustcast"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
feed-rs = "2.4.0"
iced = { version = "0.14", features = ["image", "svg", "tokio"] }
reqwest = { version = "0.13.4", features = ["blocking", "native-tls", "system-proxy"], default-features = false }
rodio = { version = "0.22.2", features = ["symphonia-mp3", "symphonia-aac"] }
